### ISSUE TITLE
缺少核心代码

### ISSUE THREAD

**Issue by lxc00215** [the-lazy-me/GenshinVoice#6]
报错host has no attribute 'XXX',经过我的分析是在这个位置。pkg.plugins包（本地）里引入一个库或者方法，但是源码里面根本就没这个包。
![image](https://github.com/the-lazy-me/GenshinVoice/assets/130938456/a0ecf9b2-ca1f-49d0-aa0e-7f414a91388e)

**Comment by the-lazy-me** [comment]
新版不能用

**Comment by lxc00215** [comment]
是的，我也发现了这个问题。这真是一个痛心的事实...

**Comment by the-lazy-me** [comment]
过几天会做更新的
